name: 'godot-ci export'
on: push

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: 1_platfomer_tutorial
  PROJECT_PATH: 1_platfomer_tutorial

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Debug
        run: |
          echo $GODOT_VERSION
          ls -al /root
          ls -al /root/.local
          ls -al /root/.local/share
          ls -al /root/.local/share/godot
          ls -al /root/.local/share/godot/export_templates
          ls -al /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.6.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
