name: 'godot-ci export'
on: push

env:
  GODOT_VERSION: 4.3

jobs:
  export-and-deploy:
    name: Export and Deploy Projects
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot Export Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: List Directories and Set PROJECTS
        id: list_dirs
        run: |
          PROJECTS=$(ls -d */ | sed 's#/##' | grep -v 'build' | tr '\n' ',' | sed 's/,$//')
          echo "PROJECTS=$PROJECTS" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo $PROJECTS

      - name: Build and Deploy All Projects
        shell: bash
        run: |
          IFS=',' read -ra MY_PROJECTS <<< "${{ env.PROJECTS }}"
          for PROJECT in "${MY_PROJECTS[@]}"; do
            pwd
            ls -al
            echo "Building and deploying $PROJECT"
            mkdir -v -p build/web/$PROJECT
            cd $PROJECT
            godot --headless --verbose --export-release "Web" ../build/web/$PROJECT/index.html
            cd ..
            
            # Deploy to GitHub Pages
            rsync -avh --delete build/web/$PROJECT/ $GITHUB_WORKSPACE/build/web/$PROJECT/
          done

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: build/web
